[I 2024-03-10 00:59:55.855 ServerApp] Package jupyterlab took 0.0000s to import
[I 2024-03-10 00:59:55.871 ServerApp] Package jupyter_lsp took 0.0160s to import
[W 2024-03-10 00:59:55.871 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-03-10 00:59:55.879 ServerApp] Package jupyter_server_terminals took 0.0071s to import
[I 2024-03-10 00:59:55.879 ServerApp] Package notebook took 0.0000s to import
[I 2024-03-10 00:59:55.880 ServerApp] Package notebook_shim took 0.0000s to import
[W 2024-03-10 00:59:55.880 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-03-10 00:59:56.385 ServerApp] Package panel.io.jupyter_server_extension took 0.5044s to import
[I 2024-03-10 00:59:56.385 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-03-10 00:59:56.386 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-03-10 00:59:56.388 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-03-10 00:59:56.389 ServerApp] notebook | extension was successfully linked.
[I 2024-03-10 00:59:56.619 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-03-10 00:59:56.619 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2024-03-10 00:59:56.653 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-03-10 00:59:56.654 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-03-10 00:59:56.655 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-03-10 00:59:56.657 LabApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.11/site-packages/jupyterlab
[I 2024-03-10 00:59:56.657 LabApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 2024-03-10 00:59:56.658 LabApp] Extension Manager is 'pypi'.
[I 2024-03-10 00:59:56.659 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-03-10 00:59:56.660 ServerApp] notebook | extension was successfully loaded.
[I 2024-03-10 00:59:56.660 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2024-03-10 00:59:56.663 ServerApp] Serving notebooks from local directory: /Users/hirendave/PythonProjects/RAGwithChromaDB
[I 2024-03-10 00:59:56.663 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2024-03-10 00:59:56.663 ServerApp] http://localhost:8888/lab?token=45c09ac770d14b1a5ab350d36d2301ff3443b8f9915ee7db
[I 2024-03-10 00:59:56.663 ServerApp]     http://127.0.0.1:8888/lab?token=45c09ac770d14b1a5ab350d36d2301ff3443b8f9915ee7db
[I 2024-03-10 00:59:56.663 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-03-10 00:59:56.666 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/hirendave/Library/Jupyter/runtime/jpserver-35791-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/lab?token=45c09ac770d14b1a5ab350d36d2301ff3443b8f9915ee7db
        http://127.0.0.1:8888/lab?token=45c09ac770d14b1a5ab350d36d2301ff3443b8f9915ee7db
[I 2024-03-10 00:59:57.040 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-03-10 01:00:03.087 LabApp] 302 GET /lab (@127.0.0.1) 1.10ms
[W 2024-03-10 01:00:30.763 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&1710012630761 (127.0.0.1): No such file or directory: Untitled.ipynb
[W 2024-03-10 01:00:30.764 ServerApp] wrote error: 'No such file or directory: Untitled.ipynb'
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.11/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_server/services/contents/handlers.py", line 121, in get
        model = await ensure_async(
                ^^^^^^^^^^^^^^^^^^^
      File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 189, in ensure_async
        result = await obj
                 ^^^^^^^^^
      File "/opt/anaconda3/lib/python3.11/site-packages/jupyter_server/services/contents/filemanager.py", line 863, in get
        raise web.HTTPError(404, "No such file or directory: %s" % path)
    tornado.web.HTTPError: HTTP 404: Not Found (No such file or directory: Untitled.ipynb)
[W 2024-03-10 01:00:30.766 ServerApp] 404 GET /api/contents/Untitled.ipynb?content=0&1710012630761 (fc7feeb8dfd8400b966fe275d6430979@127.0.0.1) 3.11ms referer=http://127.0.0.1:8888/lab
[I 2024-03-10 01:00:30.869 LabApp] Build is up to date
[I 2024-03-10 01:00:38.565 ServerApp] Creating new notebook in 
[I 2024-03-10 01:00:39.052 ServerApp] Kernel started: 77bc98fb-ee21-48d7-b941-469d77ccd91d
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-03-10 01:00:39.506 ServerApp] Connecting to kernel 77bc98fb-ee21-48d7-b941-469d77ccd91d.
[I 2024-03-10 01:00:39.510 ServerApp] Connecting to kernel 77bc98fb-ee21-48d7-b941-469d77ccd91d.
[I 2024-03-10 01:00:39.516 ServerApp] Connecting to kernel 77bc98fb-ee21-48d7-b941-469d77ccd91d.
[I 2024-03-10 01:02:39.035 ServerApp] Saving file at /Untitled.ipynb
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 818, in complete_request
    matches = self.do_complete(code, cursor_pos)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 489, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 523, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 886, in rectify_completions
    completions = list(completions)
                  ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 2828, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 2874, in _completions
    cursor_line, cursor_column = position_to_cursor(full_text, offset)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/completer.py", line 1514, in position_to_cursor
    assert 0 <= offset <= len(text) , "0 <= %s <= %s" % (offset , len(text))
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 <= 110 <= 75
[I 2024-03-10 01:04:39.164 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:06:39.206 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:08:39.244 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:08:40.111 ServerApp] Kernel restarted: 77bc98fb-ee21-48d7-b941-469d77ccd91d
[I 2024-03-10 01:08:40.118 ServerApp] Starting buffering for 77bc98fb-ee21-48d7-b941-469d77ccd91d:3a976382-0352-4474-8283-9a1e53b45578
[I 2024-03-10 01:08:40.121 ServerApp] Connecting to kernel 77bc98fb-ee21-48d7-b941-469d77ccd91d.
[I 2024-03-10 01:08:40.121 ServerApp] Restoring connection for 77bc98fb-ee21-48d7-b941-469d77ccd91d:3a976382-0352-4474-8283-9a1e53b45578
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-03-10 01:10:39.290 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:14:39.740 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:20:39.819 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:22:39.885 ServerApp] Saving file at /Untitled.ipynb
[I 2024-03-10 01:24:39.956 ServerApp] Saving file at /Untitled.ipynb
